// Leo Zhang Knowledge Base - Compiled from E:\Coding\leozhang2056
// Source of truth for AI chatbot

export const KNOWLEDGE_BASE = {
  personal: {
    name: "Yuchao Zhang (Leo Zhang)",
    nameCN: "张玉超",
    email: "leozhang2056@gmail.com",
    phone: "+64 27 385 0794",
    location: "Auckland, New Zealand (North Shore, Hillcrest)",
    visa: "Post-Study Work Visa — Open full-time work for any employer",
    linkedin: "https://www.linkedin.com/in/leo-zhang-305626280/",
    github: "https://github.com/leozhang2056",
  },

  summary: {
    core: "Full-stack software engineer with 10+ years shipping production software across Android, modern Java backends, and AI integration. Master of Computer and Information Sciences from AUT with First Class Honours.",
    android: "Android engineer with 10+ years of production mobile delivery for enterprise IM and field deployment scenarios, expert in Kotlin/Java and API integration. Strong in full lifecycle delivery from requirements to post-release support.",
    ai: "AI engineer with 10+ years in applied AI, computer vision, and full-stack delivery, focused on deployable, iterative engineering. Expert in LLM applications and vision pipelines from prototype to production.",
    java: "Backend software engineer with 10+ years in Java delivery including Spring Cloud, MyBatis, and microservices. Expert in enterprise backends for manufacturing and messaging, with focus on uptime, latency, and release rhythm.",
  },

  education: [
    {
      degree: "Master of Computer and Information Sciences",
      degreeCN: "计算机与信息科学硕士",
      institution: "Auckland University of Technology (AUT)",
      institutionCN: "奥克兰理工大学",
      location: "New Zealand",
      period: "2024-07 to 2026-02",
      status: "Completed",
      honors: "First Class Honours",
      highlights: ["Computer Vision", "Diffusion Models", "Large Language Models", "Multimodal AI"],
      thesis: "ChatClothes: Conversational Virtual Try-On with Diffusion Models",
      thesisDOI: "10.1109/IVCNZ67716.2025.11281834",
      completedEarly: "6 months early",
    },
    {
      degree: "Bachelor of Software Engineering",
      degreeCN: "软件工程学士",
      institution: "Hebei University of Science and Technology",
      institutionCN: "河北科技大学",
      location: "China",
      period: "2009-07 to 2013-06",
      highlights: ["National Scholarship", "Data Structures", "Algorithms", "Java Programming", "Database Systems"],
    },
  ],

  experience: [
    {
      company: "Auckland University of Technology",
      companyURL: "https://www.aut.ac.nz",
      location: "Auckland, New Zealand",
      role: "Master's Candidate & AI Research Assistant",
      period: "2024-07 to 2026-02",
      type: "Education/Research",
      achievements: [
        "Completed Master's at AUT (2025), building ChatClothes — multimodal virtual try-on combining OOTDiffusion with LoRA fine-tuning, YOLO-LC classification, and LLM agent via Dify workflow. Trained and fine-tuned LoRA adapters on DressCode and VITON-HD datasets. Submitted thesis 6 months early.",
        "Designed end-to-end pipeline: data preprocessing/augmentation, model training/evaluation, ComfyUI workflow orchestration, and on-device inference optimization for constrained hardware. Published at IVCNZ 2025.",
        "Worked on hyperspectral imaging and computer vision to classify kiwifruit ripeness.",
      ],
      techStack: ["AWS", "Azure", "Linux", "Docker", "Git", "PyTorch", "OpenCV", "YOLO", "LoRA", "DeepSeek", "ComfyUI", "Ollama"],
    },
    {
      company: "Chunxiao Technology Co., Ltd.",
      companyURL: "https://www.chunxiao.net/",
      location: "China",
      role: "Team Lead & Full-stack Engineer",
      period: "2019-01 to 2024-02",
      type: "Full-time",
      achievements: [
        "Architected and delivered smart factory platform for garment manufacturing — integrated RFID, electronic scales, conveyors, and barcode scanners across 5+ factory sites using Spring Cloud microservices and Docker-based CI/CD. Built Android shop-floor terminals and Vue.js web portals for hundreds of daily workers. Improved production efficiency 30%+. Awarded Hebei Provincial Science and Technology Achievement Award (2020).",
        "Built enterprise messaging platform serving 5,000 DAU with 500K+ daily messages, including SSO, file services, and permission frameworks across 5+ subsystems — migrated from legacy C++ to cloud IM, eliminating 90%+ defects.",
        "Delivered IoT projects including smart switches, Zigbee/WiFi gateways, smart power systems, and visual gateway platform for breaker control.",
        "Led Android architecture and delivery across projects — established MVVM patterns with Jetpack Compose, Coroutines, and modularisation. Shipped 8+ production Android apps and established modular architecture reused across 12+ internal projects.",
        "Partnered with product, QA, and operations to plan releases, manage risk, and improve delivery predictability. Mentored engineers through code reviews and technical guidance.",
      ],
      techStack: [".NET", "C++", "Kotlin", "Java", "Spring Cloud", "Docker", "MySQL", "Redis", "Kafka", "ActiveMQ", "Vue.js", "Android"],
    },
    {
      company: "Chunxiao Technology Co., Ltd.",
      location: "China",
      role: "Senior Android Developer",
      period: "2015-01 to 2018-12",
      type: "Full-time",
      achievements: [
        "Shipped 8+ production Android apps across live-streaming, IoT device management, and mobile workforce solutions.",
        "Designed modular Android architecture reused across 12+ internal projects, cutting code duplication by 50%+.",
        "Reduced OOM crashes on image-heavy and real-time streaming apps through memory profiling and leak detection.",
        "Managed Android app releases to Google Play and domestic app stores, handled push notification delivery with failover channels.",
      ],
      techStack: ["Kotlin", "Java", "Android SDK", "Coroutines", "NDK/JNI", "Gradle", "CI/CD"],
    },
    {
      company: "Chunxiao Technology Co., Ltd.",
      location: "China",
      role: ".NET Software Engineer",
      period: "2013-07 to 2014-12",
      type: "Full-time",
      achievements: [
        "Built media transcoding pipeline (H.264/AAC) supporting RTMP/HLS distribution using FFmpeg and C#, and developed ASP.NET backend services with SQL Server for media asset management.",
        "Implemented WebSocket-based bidirectional control for synchronized broadcast playback and real-time viewer engagement.",
        "Managed production infrastructure: SSL/TLS, multi-region failover, and media server optimization.",
        "Developed Windows Forms desktop applications for enterprise document management and full-text search.",
      ],
      techStack: [".NET", "C#", "ASP.NET", "SQL Server", "FFmpeg", "RTMP", "HLS", "WebSocket"],
    },
  ],

  skills: {
    programming: [
      { name: "Java", level: "Expert", years: 10 },
      { name: "Kotlin", level: "Advanced", years: 5 },
      { name: "Python", level: "Advanced", years: 3 },
      { name: "JavaScript", level: "Advanced", years: 6 },
      { name: "TypeScript", level: "Advanced", years: 5 },
      { name: "C#", level: "Advanced", years: 4 },
      { name: "SQL", level: "Advanced", years: 10 },
      { name: "C", level: "Intermediate", years: 4 },
      { name: "Node.js", level: "Intermediate", years: 4 },
      { name: "Bash", level: "Intermediate", years: 8 },
    ],
    mobile: [
      "Android SDK", "Kotlin", "Java", "Jetpack Compose", "MVVM", "Coroutines & Flow",
      "Hilt", "NDK/JNI", "Clean Architecture", "Gradle", "Android Security",
      "JUnit", "MockK", "Espresso", "Flutter"
    ],
    ai_ml: [
      "PyTorch", "TensorFlow", "OpenCV", "YOLO", "Diffusion Models", "LLM Fine-tuning",
      "RAG", "Prompt Engineering", "LoRA", "ComfyUI", "Computer Vision",
      "Cursor", "GitHub Copilot", "Claude Code"
    ],
    backend: [
      "Spring Cloud", "Java", "Python", "Kotlin", "REST APIs",
      "Microservices", "Event-Driven Architecture", "MySQL", "Redis",
      ".NET", "FastAPI", "MyBatis", "Hibernate", "Kafka", "ActiveMQ"
    ],
    frontend: [
      "Vue.js", "React", "HTML/CSS", "Flutter", "WordPress"
    ],
    iot: [
      "RFID", "UART/Serial", "MQTT", "Raspberry Pi", "Embedded Linux",
      "TCP/UDP Networking", "Zigbee", "GPIO", "Sensors", "Barcode Scanners"
    ],
    devops: [
      "Docker", "Jenkins", "GitHub Actions", "GitLab CI/CD", "Kubernetes",
      "Nginx", "CentOS/Ubuntu", "Azure", "AWS", "Git", "Tomcat",
      "Linux System Administration", "Windows Server"
    ],
  },

  projects: [
    {
      id: "chatclothes",
      name: "ChatClothes Virtual Try-On",
      type: "AI/ML - Master's Thesis",
      period: "2024-11 to 2025-04 (6 months, completed early)",
      role: "AI Engineer & Python Developer (Independent)",
      teamSize: 1,
      summary: "Multimodal AI virtual try-on combining diffusion generation, YOLO12n-LC classification, and LLM agent control via Dify workflow orchestration.",
      techStack: ["Python", "PyTorch", "OpenCV", "Diffusion Models", "LoRA", "LLM", "YOLO12n-LC", "FastAPI", "ComfyUI", "Ollama"],
      metrics: {
        fid: "28.5 (19% improvement)",
        classificationAccuracy: "94.2%",
        modelSize: "8x smaller than YOLO12n",
        userSuccess: "87%",
      },
      publication: "IVCNZ 2025 - DOI: 10.1109/IVCNZ67716.2025.11281834",
      awards: ["First Class Honours", "Thesis submitted 6 months early"],
      interviewQA: "Ran on two 16GB servers (Tencent Cloud free tier); LoRA fine-tuning on limited GPU; Dify workflow orchestration for LLM agent; YOLO12n-LC 94.2% accuracy with only 5MB model; published at IVCNZ 2025 with First Class Honours",
    },
    {
      id: "smart-factory",
      name: "Smart Factory System",
      type: "Industrial IoT - Enterprise",
      period: "2018-2024 (6 years)",
      role: "System Designer, Developer & Maintainer",
      teamSize: 6,
      summary: "Industrial IoT smart manufacturing platform deployed across 5+ factory sites. Spring Cloud microservices + Android shop-floor apps + Vue.js portals + IoT (RFID, scales, conveyors).",
      techStack: ["Spring Cloud", "Java", "Android", "Vue.js", "RFID", "MySQL", "Redis", "Docker", "Jenkins", "ActiveMQ", "Kafka"],
      metrics: {
        factories: "5+ sites",
        efficiency: "30%+ improvement",
        workers: "Hundreds daily users",
        team: "6-person cross-functional team",
      },
      awards: ["Hebei Provincial Science and Technology Achievement Award (2020)"],
      interviewQA: "Serial-to-WebSocket bridge for auto-filling shop-floor terminals; MySQL scaling via cloud replicas + data archival; offline SQLite + queue sync for unreliable factory networks; RFID interference mitigation in metal-rich environment",
    },
    {
      id: "enterprise-messaging",
      name: "Enterprise Messaging Platform",
      type: "Enterprise Communication / Platform",
      period: "2014-2024 (10 years, still active)",
      role: "Android Developer, System Architect & API Designer",
      teamSize: 20,
      summary: "Enterprise IM platform (Android/Web/PC) serving 5,000 DAU over 10 years. Started as sole developer, grew to 20-person team. Custom TCP protocol (WebSocket unstable), NDK TCP/UDP for sub-200ms latency. Evolved from standalone IM to multi-subsystem platform. Migrated C++ messaging to Easemob cloud, eliminating 90%+ defects. Still in use and actively growing.",
      techStack: ["Kotlin", "Java", "C/C++", "NDK", "Custom TCP/UDP", "Spring Cloud", "Node.js", "MySQL", "Redis", "FastDFS", "Easemob", "JPush"],
      metrics: {
        dau: "5,000 daily active users",
        latency: "<200ms (custom TCP protocol)",
        messages: "500K+ per day",
        downtime: "<2% over 10 years",
        evolution: "Sole developer → 20-person team",
        status: "Still active and growing",
      },
      lessons: "A successful platform doesn't start as a platform — it starts as a product that accumulates foundational data. IM → user center → feature integration + business focus + unified entry point. Organic growth from a well-anchored product is more sustainable than building a platform from day one.",
    },
    {
      id: "iot-device-management",
      name: "IoT Device Management Platform",
      type: "IoT - Product Line",
      period: "2016-2023 (7 years)",
      role: "Android Developer, Gateway Developer & Platform Designer",
      teamSize: 20,
      summary: "7-year IoT product line: smart switches and gateways sold to customers. Sole Android developer for all mobile apps. Gateway firmware for Zigbee/WiFi → MQTT. Participated in architecture design (Java Spring, time-series DB, message queue). 20-person team with majority backend.",
      techStack: ["Java", "Kotlin", "Android SDK", "Embedded Linux", "Zigbee", "WiFi", "MQTT", "UART/Serial", "Spring Cloud", "Time-series DB", "Message Queue", "Vue.js"],
      metrics: {
        duration: "7 years (2016-2023)",
        teamSize: "20 (majority backend)",
        products: "Smart switches and gateways sold to customers",
        layers: "Mobile + Gateway + Backend",
      },
      interviewQA: "Sole Android developer for 7 years; vendor SDK for gateway firmware; time-series DB (InfluxDB) for telemetry + MySQL for business data; multiple device discovery methods; backward compatibility as biggest challenge",
    },
    {
      id: "android-hotfix-framework",
      name: "Android Hotfix Framework",
      type: "Mobile Infrastructure",
      period: "2017-2023 (6 years)",
      role: "Android Framework Developer & Technical Evaluator",
      teamSize: 4,
      summary: "Evaluated and participated in an Android hotfix framework using method replacement (AndFix) and Dex merge (Tinker). Identified critical limitations: method-only replacement, no native .so swapping, ROM compatibility gaps, unsustainable version management. Led the evaluation that resulted in retiring the system in favor of staged rollout + feature flags.",
      techStack: ["Kotlin", "Java", "Method Replacement", "Dex Merge", "Staged Rollout", "Feature Flags"],
      metrics: {
        evolution: "AndFix → Tinker → retire → staged rollout + feature flags",
        decision: "Retired after evaluating maintenance cost exceeded business value",
      },
      lessons: "Technology decisions must evaluate long-term maintenance cost, engineering complexity, and business value — not just technical feasibility. Driving a 'stop doing something' decision often creates more value than building new features.",
    },
    {
      id: "iot-device-management",
      name: "IoT Device Management Platform",
      type: "IoT - Product Line",
      period: "2013-2023 (10 years)",
      role: "Full-stack Developer",
      summary: "Android app + embedded gateway firmware + Spring Cloud backend for smart switches and gateways. MQTT integration with Zigbee/WiFi devices.",
      techStack: ["Android SDK", "Embedded Linux", "Zigbee", "WiFi", "MQTT", "Spring Cloud", "Vue.js"],
      metrics: "10-year product line, multiple device types shipped including gateway and smart micro-breakers",
      interviewQA: "Sole Android developer for 7 years; vendor SDK for gateway firmware; time-series DB (InfluxDB) for telemetry + MySQL for business data; multiple device discovery methods; backward compatibility as biggest challenge",
    },
    {
      id: "live-streaming-commerce",
      name: "Live Streaming Commerce Platform",
      type: "E-commerce/Streaming",
      period: "2015-2018 (3 years)",
      summary: "Full-stack streaming platform: Android client (C++ core via NDK), ASP.NET web admin, WebSocket chat. RTMP/HLS delivery, multi-language architecture spanning 6+ languages.",
      techStack: ["Java", "Kotlin", "C++", "C#", "ASP.NET", "Node.js", "WebRTC", "RTMP", "HLS", "FFmpeg", "Python", "Lua"],
      metrics: "3-year production run, multi-language architecture (6+ languages)",
      interviewQA: "C++ core rewritten 3 times for stability; 99.5% uptime via redundancy and failover; FFmpeg multi-bitrate adaptive streaming (RTMP/HLS); Node.js Socket.IO for 1000+ concurrent chat connections",
    },
    {
      id: "forest-patrol",
      name: "Forest Patrol GIS",
      type: "Mobile GIS",
      period: "2021-2022 (1 year)",
      summary: "Offline-first Android GIS app for forest rangers in no-signal areas. Custom offline maps, GPS tracking, incident reporting with deferred sync. Supports risk event reporting for fire hazards, pest/disease, and land occupation.",
      techStack: ["Java", "Kotlin", "Android SDK", "ArcGIS", "SQLite", "GPS", "Offline Maps", "Tinker"],
      metrics: "Deployed for forestry department, reliable zero-connectivity operation",
      interviewQA: "GCJ-02/WGS-84/BD-09 coordinate conversion for China map systems; offline-first SQLite with deferred sync when signal returns; GDAL/Geos/Shapely for GIS processing; dead reckoning for GPS signal loss under dense forest canopy",
    },
    {
      id: "school-attendance",
      name: "School Face Recognition Attendance System",
      type: "IoT / Education",
      period: "2020-2021 (1 year)",
      role: "Android Developer",
      teamSize: 3,
      summary: "School face recognition attendance with local on-device comparison using ArcSoft SDK. 3-person team — I built the Android terminal with face recognition, liveness detection, and gate control. 1-2s per student, 99%+ accuracy, real-time parent notifications. Deployed across multiple schools.",
      techStack: ["Java", "Kotlin", "Android SDK", "ArcSoft SDK", "OpenCV", "Spring Cloud", "JPush", "MySQL", "Redis"],
      metrics: {
        recognition: "1-2 seconds per student (local comparison)",
        accuracy: "99%+",
        schools: "3+ deployed",
        notification: "Real-time parent push",
      },
      interviewQA: "ArcSoft SDK on-device comparison (network reliability + speed); confidence thresholds for similar students; 2D liveness detection; fixed mount camera design; templates stored both locally and in cloud",
    },
    {
      id: "smart-power",
      name: "Smart Power Management System",
      type: "IoT / Energy Management",
      period: "2019-2022 (3 years)",
      role: "Java Backend & Android Developer",
      teamSize: 20,
      summary: "Smart power platform for factories and buildings. 20-person company-wide project. Monitor per-load electrical parameters, remote control, alarm policies. 15% energy saving, sub-second alarm, 99.9% data collection rate, 3+ parks deployed.",
      techStack: ["Java", "Spring Cloud", "Modbus", "RS485", "MQTT", "InfluxDB", "Flink", "Vue.js", "ECharts", "Redis", "RabbitMQ"],
      metrics: {
        energySaving: "15% average reduction",
        alarmSpeed: "<1 second",
        dataAccuracy: "99.9% collection rate",
        parks: "3+ deployed",
        teamSize: "20 people",
      },
      interviewQA: "Flink for real-time alerting + aggregation; multi-tenant isolation (park prefix + tenant_id); 0.1% data loss from network/firmware; 15% saving measured vs historical baseline; modular protocol adapter layer",
    },
    {
      id: "visit-system",
      name: "Visit Booking & Access Management",
      type: "Enterprise System",
      period: "2020-2022 (2 years)",
      summary: "Multi-terminal platform: admin booking, face recognition terminals, visitor WeChat mini-program, WebRTC sessions.",
      techStack: ["Spring Cloud", "Android", "WeChat Mini Program", "WebRTC", "Face Recognition", "MySQL", "Redis"],
      metrics: "99.5% face recognition accuracy, <1s verification, 30% efficiency gain",
      interviewQA: "WebRTC video visits with server-side time enforcement; face recognition under 1 second with 99.5% accuracy; pandemic contactless mode with remote video visits; complete audit trail for prison compliance requirements",
    },
    {
      id: "picture-book-locker",
      name: "Picture Book Locker",
      type: "IoT/Hardware",
      period: "2020-2023 (3 years)",
      summary: "Smart library locker with Android control cabinet (locks, UV, sensors) + borrower app + face/QR authentication.",
      techStack: ["Java", "Kotlin", "Android SDK", "Face Recognition", "ZXing", "ARM Board", "UART/RS485", "GSM"],
      metrics: "<3s borrowing, multiple schools, 0% book loss rate",
      interviewQA: "UART/RS485/GPIO controlling 10+ peripherals (locks, UV, sensors); 3-second borrow via parallelization and preloaded face templates; managed colleague resignation with scope rebalancing; UV safety interlock for book sterilization",
    },
    {
      id: "visual-gateway",
      name: "Smart Gateway / Breaker Control Platform",
      type: "IoT / Industrial",
      period: "2022-2024 (2 years)",
      role: "Android Gateway Developer & Architect",
      teamSize: 4,
      summary: "Smart gateway controlling non-networked circuit breakers via RS232. Each gateway manages up to 70 breakers. Telemetry, remote control, local alerting, cloud reporting. Connects to Smart Power Management Platform. 4-person team — I developed the Android gateway and designed the architecture.",
      techStack: ["Java", "Kotlin", "Android SDK", "RS232", "Modbus RTU", "MQTT", "InfluxDB", "MySQL", "Vue.js", "ECharts"],
      metrics: {
        capacity: "Up to 70 breakers per gateway",
        telemetry: "Real-time current/voltage/power/energy",
        availability: "24/7 edge operation",
        integration: "Connects to Smart Power Platform",
      },
      interviewQA: "Android chosen for existing ecosystem; 70 devices polled in ~1-1.5s (optimized to 200-300ms with 4 ports); edge alerting without cloud; SQLite persistence on crash recovery; loosely coupled via MQTT",
    },
    {
      id: "banknote-paper-mill",
      name: "High-Security Manufacturing System Integration",
      type: "Enterprise/Manufacturing IT",
      period: "2018-2020 (intermittent)",
      role: "Solution Designer, Deployer & Data Integration Engineer",
      teamSize: 3,
      summary: "Manufacturing information systems for a high-security banknote paper production facility. Designed gateway to aggregate data from 7-8 legacy hardware types via serial ports (9600/115200 baud). Synchronized scattered databases to unified BI layer (FineBI). Deployed UHF scanners for paper axis tracking despite metal wire signal interference.",
      techStack: ["SQL", "Pentaho Data Integration (Kettle)", "ETL", "Serial Port", "UHF Scanning", "FineBI", "Linux", "MySQL"],
      metrics: {
        hardwareDevices: "7-8 types, ~12 devices, 2 gateways",
        serialBaud: "9600 / 115200",
        reportingInterval: "~30 seconds",
        biTool: "FineBI (帆软)",
        siteApproval: "~1 week lead time",
        participation: "Intermittent",
      },
      interviewQA: "Devices used proprietary protocols (not Modbus); modular parser approach for 7-8 device types; gateway was embedded Linux with multiple serial ports; 30-second interval was practical for manufacturing; FineBI selected for on-premise air-gapped deployment; site approval ~1 week through security department; debugging required careful off-site preparation; UHF interference solved physically with antenna calibration",
    },
    {
      id: "exhibition-robot",
      name: "Exhibition Service Robot",
      type: "AI / Robotics",
      period: "2019",
      role: "Android Developer",
      teamSize: 4,
      summary: "Intelligent service robot for exhibitions and malls. Robot provided SDK for control; team built features on top: navigation, product introduction, face recognition with check-in, knowledge base, and voice interaction. 4-person team — I developed the Android interaction interface and integrated robot SDK features. Deployed at client exhibition, still in use.",
      techStack: ["Java", "Kotlin", "ROS", "SLAM", "LiDAR", "OpenCV", "ASR/TTS", "Face Recognition", "Android SDK", "Spring Cloud", "MQTT"],
      metrics: {
        navigation: "Centimeter-level precision (LiDAR SLAM)",
        faceRecognition: ">98% accuracy",
        voiceUnderstanding: ">90% intent understanding",
        availability: "7x24 continuous operation",
        deployment: "Client exhibition, still in use",
      },
      interviewQA: "4-person team; bought robot with SDK (not built from scratch); Android interaction UI on vendor SDK; ArcSoft face recognition + iFlytek voice; deployed at client exhibition hall",
    },
    {
      id: "broadcast-control",
      name: "Smart Broadcast Control Platform",
      type: "Digital Signage / IoT Device Management",
      period: "2020 (2 months, ahead of schedule)",
      role: "Project Manager, System Designer & Android Team Lead",
      teamSize: 9,
      summary: "Digital Signage platform for centralized ad delivery across 1000+ retail display devices. Three-component architecture: Vue.js Admin Console, Customer Portal, Spring Boot/Cloud backend, Android Device Client. MQTT broadcast with high-concurrency handling, multi-screen adaptation, campaign scheduling, device fleet management, and offline cache/recovery.",
      techStack: ["Java", "Kotlin", "Spring Boot", "Spring Cloud", "Vue.js", "Android SDK", "MQTT", "MySQL", "ExoPlayer", "WebSocket"],
      metrics: {
        devices: "1000+ display devices",
        teamSize: "9 (3 backend, 2 frontend, 2 mobile, 1 designer, 1 QA)",
        deliveryTime: "2 months, ahead of schedule",
        communication: "MQTT broadcast with high-concurrency handling",
        businessScenario: "Retail stores (bookstores, clothing stores, design shops)",
      },
      interviewQA: "Peak 1000-1500 connections; staggered broadcasts to avoid burst; QoS 1 for tasks; offline devices sync current state on reconnect; 2-week sprints with OpenAPI spec; separate Admin Console vs Customer Portal for different user groups; ~80% effort reduction from days to minutes; simple pairing code for non-technical customers",
    },
    {
      id: "boobit",
      name: "Boobit Crypto Trading Platform",
      type: "Fintech/Mobile",
      period: "2022",
      summary: "Cryptocurrency trading platform mobile app with real-time market data via WebSocket, coin search, exchange operations, and secure wallet management.",
      techStack: ["Android", "Kotlin", "MVVM", "Retrofit", "WebSocket", "Jetpack Compose", "Room"],
      metrics: "Real-time market data updates, secure wallet with encryption",
      interviewQA: "BigDecimal for financial precision; 3-layer security (HTTPS + HMAC-SHA256 + AES); WebSocket reconnect with fallback polling; sole developer with testing discipline; greenfield rebuild using Jetpack Compose",
    },
    {
      id: "chinese-herbal-recognition",
      name: "AI Data Annotation & Model Training Platform",
      type: "AI Platform / MLOps",
      period: "2019",
      role: "Platform Designer, AI Prototype Developer",
      teamSize: 4,
      summary: "General-purpose AI platform for data annotation and model training. Validated with Chinese herbal recognition demo (20 categories, ~50 images/class). Prototype → handoff → launch, but not maintained afterwards.",
      techStack: ["Python", "TypeScript", "FastAPI", "Vue.js", "YOLOv4", "ResNet", "MobileNetV3", "EfficientNet", "MySQL", "Docker", "GPU Training"],
      metrics: {
        demoCategories: "20 herbal types",
        imagesPerClass: "~50",
        modelsTested: "4 (YOLOv4, ResNet, MobileNetV3, EfficientNet)",
        evaluationCriteria: "Top-1 Accuracy, Macro F1, Worst-class Recall, P95 Latency",
        outcome: "Developed and launched, not maintained",
      },
      interviewQA: "API contracts via FastAPI Swagger with Pydantic; MobileNetV3 best for small dataset; data augmentation + transfer learning for overfitting; thresholds from benchmarking; business priority shift ended maintenance; hardest part was designing flexible abstraction layers for general-purpose platform",
    },
    {
      id: "device-maintenance-prediction",
      name: "Device Maintenance Prediction",
      type: "AI/Predictive Maintenance",
      period: "2023",
      summary: "AI platform for equipment predictive maintenance. Uses historical logs, fault records, and runtime indicators to model aging patterns and predict maintenance schedules. Outputs risk scoring and data-driven scheduling.",
      techStack: ["SparkNet", "Random Forest", "Feature Engineering", "Time-series Analysis"],
      metrics: "Multi-model comparison with aging trend analysis and risk scoring",
      interviewQA: "Manufacturing equipment prediction from service logs and fault records; missing data imputation for incomplete records; feature engineering from raw service logs; time-based cross-validation to avoid data leakage; shifted from fixed-cycle to predictive maintenance scheduling",
    },
    {
      id: "field-weighing-access-control",
      name: "Highway Toll Station Vehicle Inspection System",
      type: "Enterprise System / Industrial IoT",
      period: "2015-2017 (2 years)",
      role: "Developer",
      summary: "Vehicle inspection system for highway toll stations. C# application integrating electronic scales for vehicle weighing, real-time data storage, overload alarm alerts, and customer system integration for automatic invoice generation.",
      techStack: ["C#", "Electronic Scale Integration", "Alarm System", "Invoicing Integration"],
      metrics: "Deployed at highway toll station with weighing, alarms, and invoicing",
      interviewQA: "C# Windows Forms; RS232 serial scale communication; invoicing API integration; configurable alarm thresholds; stabilization algorithm for scale readings",
    },
    {
      id: "patent-search-system",
      name: "Patent Search System",
      type: "Enterprise Desktop Application",
      period: "2014",
      role: "Sole Developer",
      summary: "Early-career solo project: built entire enterprise patent management system myself — .NET desktop app with Lucene.NET full-text search, SQL Server, Excel batch processing. 10,000+ patents, <2s search, 50+ daily users.",
      techStack: ["C#", ".NET Framework 2.0", "Windows Forms", "SQL Server 2008", "Lucene.NET 2.9", "EPPlus", "ADO.NET"],
      metrics: {
        patents: "10,000+ managed",
        search: "<2s response time",
        users: "50+ daily users",
        team: "Solo project",
      },
      interviewQA: "Solo early-career project; Chinese analyzer for Lucene.NET; Excel batch import via EPPlus; SQL Server concurrent access; would use Elasticsearch + web UI today",
    },
  ],

  certifications: [
    { name: "Software Design Engineer Certificate", authority: "China Qualification Authority", year: 2019 },
    { name: "IoT Fundamentals", authority: "Xi'an Jiaotong University", year: 2020 },
  ],

  awards: [
    { name: "First Class Honours", authority: "AUT", year: 2025, category: "Master's Degree" },
    { name: "Science and Technology Achievement Award", authority: "Hebei, China", year: 2020, category: "Smart Manufacturing" },
    { name: "National Scholarship", authority: "Hebei University of Science and Technology", year: 2013, category: "Academic" },
  ],

  publications: [
    {
      title: "ChatClothes: Conversational Virtual Try-On with Diffusion Models",
      venue: "IVCNZ 2025",
      year: 2025,
      type: "Conference Paper",
      doi: "10.1109/IVCNZ67716.2025.11281834",
    },
    {
      title: "Clothes Recognition Based on Lightweight Deep Learning Models",
      venue: "IGI Global — Aesthetics in Creative Technology",
      year: 2026,
      type: "Book Chapter",
      status: "Under Review",
    },
  ],

  languages: [
    { language: "Chinese (Mandarin)", proficiency: "Native" },
    { language: "English", proficiency: "Professional Working" },
  ],

  keywords: [
    "Java", "Kotlin", "Android", "Spring Cloud", "AI", "Machine Learning", "PyTorch",
    "Python", "Microservices", "Docker", "Full-stack", "Computer Vision", "LLM",
    "Agile", "CI/CD", "IoT", "RFID", "Enterprise Messaging", "Industrial IoT",
    "Edge Computing", "Virtual Try-On", "Diffusion Models", "YOLO", "LoRA"
  ],
};

export type KnowledgeBase = typeof KNOWLEDGE_BASE;
